### ISSUE TITLE
Add license screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#625]
**Idea Description**
We can add it in about module.
And please open it.

**Reference images and links**
https://developers.google.com/android/guides/opensource

**Comment by yuuhanasaki39** [comment]
I'd like to try!  ✋

**Comment by mhidaka** [comment]
@yuuhanasaki39 Thanks, please go ahead

**Comment by takahirom** [comment]
@yuuhanasaki39 Do you think you will have time tomorrow? If not please let us know 🙏

**Comment by yuuhanasaki39** [comment]
@takahirom Hello! In conclusion, I don't know how long it will take.
There is a problem that has been bothering me. I will share it now.

**Comment by takahirom** [comment]
@yuuhanasaki39 Thank you for sharing me!

**Comment by takahirom** [comment]
You can use Japanese if you want 👍

**Comment by yuuhanasaki39** [comment]
@takahirom 
では日本語で失礼します。

現在、動画のようにLicenseボタン押下時にクラッシュする状態です。
https://user-images.githubusercontent.com/111329363/191793036-e725e542-378a-48e1-9b5b-b6d612fd259e.mov

行った実装について、
各gradleのファイルにライブラリを追加してビルドを通した後、
`feature/about/~/About.kt`内のLicenseボタン押下時のイベントで
`onClick = { context.startActivity(Intent(context, OssLicensesMenuActivity::class.java)) }`
と追加しました。

クラッシュログは以下のとおりです。
```
FATAL EXCEPTION: main
Process: io.github.droidkaigi.confsched2022.dev, PID: 8786
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.droidkaigi.confsched2022.dev/com.google.android.gms.oss.licenses.OssLicensesMenuActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7898)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
at androidx.appcompat.app.AppCompatDelegateImpl.initWindowDecorActionBar(AppCompatDelegateImpl.java:556)
at androidx.appcompat.app.AppCompatDelegateImpl.getSupportActionBar(AppCompatDelegateImpl.java:543)
at androidx.appcompat.app.AppCompatDelegateImpl.invalidateOptionsMenu(AppCompatDelegateImpl.java:1226)
at androidx.appcompat.app.AppCompatActivity.invalidateOptionsMenu(AppCompatActivity.java:314)
at androidx.activity.ComponentActivity.invalidateMenu(ComponentActivity.java:568)
at androidx.activity.ComponentActivity$$ExternalSyntheticLambda0.run(Unknown Source:2)
at androidx.core.view.MenuHostHelper.addMenuProvider(MenuHostHelper.java:133)
at androidx.activity.ComponentActivity.addMenuProvider(ComponentActivity.java:546)
at androidx.fragment.app.FragmentActivity$HostCallbacks.addMenuProvider(FragmentActivity.java:736)
at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:2793)
at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:117)
at androidx.fragment.app.FragmentActivity.lambda$init$3$androidx-fragment-app-FragmentActivity(FragmentActivity.java:140)
at androidx.fragment.app.FragmentActivity$$ExternalSyntheticLambda3.onContextAvailable(Unknown Source:2)
at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:362)
at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:217)
at com.google.android.gms.oss.licenses.OssLicensesMenuActivity.onCreate(Unknown Source:2)
at android.app.Activity.performCreate(Activity.java:8290)
at android.app.Activity.performCreate(Activity.java:8269)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813) 
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:201) 
at android.os.Looper.loop(Looper.java:288) 
at android.app.ActivityThread.main(ActivityThread.java:7898) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

`You need to use a Theme.AppCompat theme`と出ているように、OssLicensesMenuActivityがAppCompatActivityを継承しているので、Theme.AppCompat系のテーマを割り当ててあげるのが良い気がしてますが、具体的な実装方法がわからず手が止まっています。

なにか参考になる情報があれば共有していただけると嬉しいです！
よろしくおねがいします！

（まだpushできていないので、後ほど追記します）

**Comment by NUmeroAndDev** [comment]
@yuuhanasaki39 
AndroidManifest で application に対して指定している 
`android:theme="@style/Theme.DroidKaigi.SplashTheme"` がライセンスの Activity に対しても適用されていて、その `SplashTheme` が AppCompat の Theme でないから落ちるようになっていますね 👀 

回避手段は下の 2 パターンありそうなので、試してもらっていい感じになりそうなものでお願いしてもいいでしょうか 🙏 

- AndroidManifest で `Theme.DroidKaigi` をライセンスの Activity に指定する
  - もしかしたらこちらは色がデフォルトの紫が出てくるかもしれないので、 `Theme.DroidKaigi` の色も変更する必要がありそうです…
- AndroidManifest で `Theme.AppCompat` をライセンスの Activity に指定する
  - 黒のテーマになるはずなので簡単なパターンです

**Comment by takahirom** [comment]
For your reference
https://developers.google.com/android/guides/opensource#apply-theme-to-activity

```
<application android:theme="@style/AppTheme" ...>
    <activity
        android:name="com.google.android.gms.oss.licenses.OssLicensesMenuActivity"
        android:theme="@style/AppTheme" />
    <activity
        android:name="com.google.android.gms.oss.licenses.OssLicensesActivity"
        android:theme="@style/AppTheme" />
</application>
```

**Comment by yuuhanasaki39** [comment]
ありがとうございます！やってみます！

**Comment by yuuhanasaki39** [comment]
It worked. Thank you! 👍
